<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<?PHP
include "pageheader.php";
?>
<html>
<head>
<title>Zufallsbild - Übersicht</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="../stylesheets/styles.css" rel="Stylesheet" type="text/css">
<script type="text/javascript" src="../javascript/analyticstracking.js"></script>
</head>
<body>
	<h2>Legal Notice</h2>

	<h3>Information according to §5 TMG</h3>
	<p>
		Jörg Eisfeld<br>Merseburger Str. 8<br>80993 München<br>Germany
	</p>

	<h3>Contact:</h3>
	<p>
		Phone: +49-176-20928331 <br> E-Mail:
		<a href="mailto:Jörg Eisfeld<augendiagnose@jeisfeld.de> ">augendiagnose@jeisfeld.de</a>
	</p>

	<h3>Disclaimer - Legal Notice</h3>

	<h4>§1 Limitation of Liability</h4>
	<p>The contents of this website are created with the utmost care. The provider does not accept Warranty for the
		accuracy, completeness and timeliness of the content provided. The use of the contents of Website is at the user's own
		risk.</p>
	<p>As a service provider we are in accordance with § 7 Abs.1 TMG for own content on these pages after the general
		Laws responsible. According to §§ 8 to 10 TMG, however, we as a service provider are not obliged to transmit or to
		monitor any stored third-party information or to investigate circumstances that are unlawful Point out activity.
		Obligations to remove or block the use of information according to the general Laws remain unaffected. A liability in
		this regard, however, is only from the date of knowledge concrete infringement possible. Upon notification of
		appropriate violations, we will this content remove immediately.</p>

	<h4>§2 External Links</h4>
	<p>This website contains links to third-party websites ("external links") over which we have no influence to have.
		These websites are the responsibility of the respective operators. The provider has at the first time Linking the
		external links to check the external content for possible legal violations. To that At the time there were no legal
		violations. The provider has no influence on the current and future Design and content of the linked pages. Setting
		external links does not mean that the Provider owns the content behind the link or reference. A constant control of
		the external links is not reasonable for the offerer without concrete references to legal offenses. Be aware of legal
		violations however, such external links deleted immediately.</p>

	<h4>§3 Copyright and ancillary copyright</h4>
	<p>The content published on this website is subject to German copyright and ancillary copyright. The Reproduction,
		editing, distribution and any kind of exploitation outside the limits of copyright require the written consent of the
		respective author or creator. Downloads and copies of this page are only for private, non-commercial use. As far as
		the contents on this side are not from the operator were created, the copyrights of third parties are respected. In
		particular, third party content as such characterized. Should you still be aware of a copyright infringement, we ask
		for one corresponding note. Upon notification of violations, we will remove such content immediately.</p>

	<h4>§4 Privacy Policy - Google Analytics</h4>

	<p>
		This website uses Google Analytics, a web analysis service of Google Inc, (1600 Amphitheatre Parkway Mountain View, CA
		94043, USA; &quot;Google&quot;). The use includes the &quot;Universal Analytics&quot; operating mode. This facilitates
		the assignment of data, sessions and interactions across several devices to a pseudonymous user ID and thus the
		analysis of a user's activities across devices. This data protection notice is provided by
		<a href="https://www.intersoft-consulting.de" target="_blank">www.intersoft-consulting.de</a>
		.
	</p>

	<p>
		Google Analytics uses &quot;cookies&quot;, which are text files placed on your computer, to allow the website operator
		to analyze how users use the site. The information generated by the cookie about your use of this website is usually
		transferred to a Google server in the USA and stored there. However, if IP anonymisation is activated on this website,
		Google will reduce your IP address within Member States of the European Union or in other states party to the
		Agreement on the European Economic Area beforehand. Only in exceptional cases will the full IP address be transmitted
		to a Google server in the USA and shortened there. The IP address transmitted by your browser in the context of Google
		Analytics is not merged with other Google data. On behalf of the operator of this website, Google will use this
		information to evaluate your use of the website, to compile reports on website activity and to provide the website
		operator with other services related to website and Internet use. Our legitimate interest in data processing also lies
		in these purposes. The legal basis for the use of Google Analytics is § 15 para. 3 TMG and Art. 6 para. 1 lit. f GDPR.
		The data sent by us and linked to cookies, user-identifiers (e.g. User-IDs) or advertising-identifiers are
		automatically deleted after 14 months. Data whose retention period has been reached is automatically deleted once a
		month. For more information on terms of use and data protection, please visit
		<a href="https://www.google.com/analytics/terms/gb.html" target="_blank">https://www.google.com/analytics/terms/gb.html</a>
		or
		<a href="https://policies.google.com/?hl=en" target="_blank">https://policies.google.com/?hl=en</a>
		.
	</p>

	<p>
		You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if
		you do this you may not be able to use the full functionality of this website. You can also prevent Google from
		collecting the data generated by the cookie and relating to your use of the website (including your IP address) and
		from processing this data by Google by downloading and installing the
		<a href="https://tools.google.com/dlpage/gaoptout?hl=en" target="_blank">Browser Add-on</a>
		. Opt-out cookies prevent the future collection of your data when you visit this website. To prevent Universal
		Analytics from collecting data across several devices, you must opt-out on all systems used. If you click here, the
		opt-out cookie will be set:
		<a href="javascript:gaOptout()">
			<strong>Disable Google Analytics</strong>
		</a>
	</p>
</body>
</html>